# Generated by Django 5.2.11 on 2026-02-19 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayThrough',
            fields=[
                ('playthrough_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.UUIDField(db_index=True)),
                ('game_slug', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('completed', 'Completed'), ('interrupted', 'Interrupted'), ('cancelled', 'Cancelled')], max_length=20)),
                ('log_path', models.CharField(max_length=500)),
                ('step_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('checkpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('playthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='wsz6_play.playthrough')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
