# Generated by Django 5.2.11 on 2026-02-19 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brief_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('dev', 'Development'), ('beta', 'Beta'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='dev', max_length=20)),
                ('min_players', models.PositiveIntegerField(default=1)),
                ('max_players', models.PositiveIntegerField(default=10)),
                ('pff_path', models.CharField(blank=True, max_length=500)),
                ('metadata_json', models.JSONField(default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('beta_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
