# Generated by Django 5.2.11 on 2026-02-21 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True)),
                ('playthrough_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('log_frame_index', models.IntegerField(blank=True, null=True)),
                ('annotation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_key', 'playthrough_id', 'log_frame_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_api_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
