# Generated by Django 5.2.11 on 2026-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wszuser',
            name='allowed_games',
            field=models.ManyToManyField(blank=True, related_name='explicitly_allowed_users', to='games_catalog.game'),
        ),
        migrations.AddField(
            model_name='wszuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='wszuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
