# Generated by Django 5.2.11 on 2026-02-19 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open (lobby)'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='open', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(default=dict)),
                ('gdm_path', models.CharField(blank=True, max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games_catalog.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_sessions', to=settings.AUTH_USER_MODEL)),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuation_sessions', to='sessions_log.gamesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
